package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	InventoryConfigurations        []InventoryConfiguration        `json:",omitempty"`
	DomainName                     *string                         `json:",omitempty"`
	BucketEncryption               *BucketEncryption               `json:",omitempty"`
	WebsiteURL                     *string                         `json:",omitempty"`
	NotificationConfiguration      *NotificationConfiguration      `json:",omitempty"`
	WebsiteConfiguration           *WebsiteConfiguration           `json:",omitempty"`
	LifecycleConfiguration         *LifecycleConfiguration         `json:",omitempty"`
	DualStackDomainName            *string                         `json:",omitempty"`
	VersioningConfiguration        *VersioningConfiguration        `json:",omitempty"`
	MetricsConfigurations          []MetricsConfiguration          `json:",omitempty"`
	AccessControl                  *string                         `json:",omitempty"`
	AnalyticsConfigurations        []AnalyticsConfiguration        `json:",omitempty"`
	AccelerateConfiguration        *AccelerateConfiguration        `json:",omitempty"`
	PublicAccessBlockConfiguration *PublicAccessBlockConfiguration `json:",omitempty"`
	BucketName                     *string                         `json:",omitempty"`
	RegionalDomainName             *string                         `json:",omitempty"`
	CorsConfiguration              *CorsConfiguration              `json:",omitempty"`
	ObjectLockConfiguration        *ObjectLockConfiguration        `json:",omitempty"`
	ObjectLockEnabled              *bool                           `json:",omitempty"`
	LoggingConfiguration           *LoggingConfiguration           `json:",omitempty"`
	Id                             *string                         `json:",omitempty"`
	Arn                            *string                         `json:",omitempty"`
	ReplicationConfiguration       *ReplicationConfiguration       `json:",omitempty"`
	Tags                           []Tag                           `json:",omitempty"`
}

// InventoryConfiguration is autogenerated from the json schema
type InventoryConfiguration struct {
	Destination            *Destination `json:",omitempty"`
	OptionalFields         []string     `json:",omitempty"`
	IncludedObjectVersions *string      `json:",omitempty"`
	Enabled                *bool        `json:",omitempty"`
	Id                     *string      `json:",omitempty"`
	Prefix                 *string      `json:",omitempty"`
	ScheduleFrequency      *string      `json:",omitempty"`
}

// Destination is autogenerated from the json schema
type Destination struct {
	BucketArn       *string `json:",omitempty"`
	BucketAccountId *string `json:",omitempty"`
	Format          *string `json:",omitempty"`
	Prefix          *string `json:",omitempty"`
}

// BucketEncryption is autogenerated from the json schema
type BucketEncryption struct {
	ServerSideEncryptionConfiguration []ServerSideEncryptionRule `json:",omitempty"`
}

// ServerSideEncryptionRule is autogenerated from the json schema
type ServerSideEncryptionRule struct {
	ServerSideEncryptionByDefault *ServerSideEncryptionByDefault `json:",omitempty"`
}

// ServerSideEncryptionByDefault is autogenerated from the json schema
type ServerSideEncryptionByDefault struct {
	SSEAlgorithm   *string `json:",omitempty"`
	KMSMasterKeyID *string `json:",omitempty"`
}

// NotificationConfiguration is autogenerated from the json schema
type NotificationConfiguration struct {
	QueueConfigurations  []QueueConfiguration  `json:",omitempty"`
	LambdaConfigurations []LambdaConfiguration `json:",omitempty"`
	TopicConfigurations  []TopicConfiguration  `json:",omitempty"`
}

// QueueConfiguration is autogenerated from the json schema
type QueueConfiguration struct {
	Event  *string             `json:",omitempty"`
	Filter *NotificationFilter `json:",omitempty"`
	Queue  *string             `json:",omitempty"`
}

// NotificationFilter is autogenerated from the json schema
type NotificationFilter struct {
	S3Key *S3KeyFilter `json:",omitempty"`
}

// S3KeyFilter is autogenerated from the json schema
type S3KeyFilter struct {
	Rules []FilterRule `json:",omitempty"`
}

// FilterRule is autogenerated from the json schema
type FilterRule struct {
	Value *string `json:",omitempty"`
	Name  *string `json:",omitempty"`
}

// LambdaConfiguration is autogenerated from the json schema
type LambdaConfiguration struct {
	Function *string             `json:",omitempty"`
	Event    *string             `json:",omitempty"`
	Filter   *NotificationFilter `json:",omitempty"`
}

// TopicConfiguration is autogenerated from the json schema
type TopicConfiguration struct {
	Event  *string             `json:",omitempty"`
	Topic  *string             `json:",omitempty"`
	Filter *NotificationFilter `json:",omitempty"`
}

// WebsiteConfiguration is autogenerated from the json schema
type WebsiteConfiguration struct {
	RoutingRules          []RoutingRule          `json:",omitempty"`
	IndexDocument         *string                `json:",omitempty"`
	RedirectAllRequestsTo *RedirectAllRequestsTo `json:",omitempty"`
	ErrorDocument         *string                `json:",omitempty"`
}

// RoutingRule is autogenerated from the json schema
type RoutingRule struct {
	RedirectRule         *RedirectRule         `json:",omitempty"`
	RoutingRuleCondition *RoutingRuleCondition `json:",omitempty"`
}

// RedirectRule is autogenerated from the json schema
type RedirectRule struct {
	ReplaceKeyWith       *string `json:",omitempty"`
	HttpRedirectCode     *string `json:",omitempty"`
	Protocol             *string `json:",omitempty"`
	HostName             *string `json:",omitempty"`
	ReplaceKeyPrefixWith *string `json:",omitempty"`
}

// RoutingRuleCondition is autogenerated from the json schema
type RoutingRuleCondition struct {
	KeyPrefixEquals             *string `json:",omitempty"`
	HttpErrorCodeReturnedEquals *string `json:",omitempty"`
}

// RedirectAllRequestsTo is autogenerated from the json schema
type RedirectAllRequestsTo struct {
	Protocol *string `json:",omitempty"`
	HostName *string `json:",omitempty"`
}

// LifecycleConfiguration is autogenerated from the json schema
type LifecycleConfiguration struct {
	Rules []Rule `json:",omitempty"`
}

// Rule is autogenerated from the json schema
type Rule struct {
	Status                            *string                         `json:",omitempty"`
	NoncurrentVersionExpirationInDays *int                            `json:",omitempty"`
	Transitions                       []Transition                    `json:",omitempty"`
	TagFilters                        []TagFilter                     `json:",omitempty"`
	NoncurrentVersionTransitions      []NoncurrentVersionTransition   `json:",omitempty"`
	Prefix                            *string                         `json:",omitempty"`
	NoncurrentVersionTransition       *NoncurrentVersionTransition    `json:",omitempty"`
	ExpirationDate                    *string                         `json:",omitempty"`
	ExpirationInDays                  *int                            `json:",omitempty"`
	Transition                        *Transition                     `json:",omitempty"`
	Id                                *string                         `json:",omitempty"`
	AbortIncompleteMultipartUpload    *AbortIncompleteMultipartUpload `json:",omitempty"`
}

// Transition is autogenerated from the json schema
type Transition struct {
	TransitionDate   *string `json:",omitempty"`
	TransitionInDays *int    `json:",omitempty"`
	StorageClass     *string `json:",omitempty"`
}

// TagFilter is autogenerated from the json schema
type TagFilter struct {
	Value *string `json:",omitempty"`
	Key   *string `json:",omitempty"`
}

// NoncurrentVersionTransition is autogenerated from the json schema
type NoncurrentVersionTransition struct {
	StorageClass     *string `json:",omitempty"`
	TransitionInDays *int    `json:",omitempty"`
}

// AbortIncompleteMultipartUpload is autogenerated from the json schema
type AbortIncompleteMultipartUpload struct {
	DaysAfterInitiation *int `json:",omitempty"`
}

// VersioningConfiguration is autogenerated from the json schema
type VersioningConfiguration struct {
	Status *string `json:",omitempty"`
}

// MetricsConfiguration is autogenerated from the json schema
type MetricsConfiguration struct {
	TagFilters []TagFilter `json:",omitempty"`
	Id         *string     `json:",omitempty"`
	Prefix     *string     `json:",omitempty"`
}

// AnalyticsConfiguration is autogenerated from the json schema
type AnalyticsConfiguration struct {
	TagFilters           []TagFilter           `json:",omitempty"`
	StorageClassAnalysis *StorageClassAnalysis `json:",omitempty"`
	Id                   *string               `json:",omitempty"`
	Prefix               *string               `json:",omitempty"`
}

// StorageClassAnalysis is autogenerated from the json schema
type StorageClassAnalysis struct {
	DataExport *DataExport `json:",omitempty"`
}

// DataExport is autogenerated from the json schema
type DataExport struct {
	Destination         *Destination `json:",omitempty"`
	OutputSchemaVersion *string      `json:",omitempty"`
}

// AccelerateConfiguration is autogenerated from the json schema
type AccelerateConfiguration struct {
	AccelerationStatus *string `json:",omitempty"`
}

// PublicAccessBlockConfiguration is autogenerated from the json schema
type PublicAccessBlockConfiguration struct {
	RestrictPublicBuckets *bool `json:",omitempty"`
	IgnorePublicAcls      *bool `json:",omitempty"`
	BlockPublicPolicy     *bool `json:",omitempty"`
	BlockPublicAcls       *bool `json:",omitempty"`
}

// CorsConfiguration is autogenerated from the json schema
type CorsConfiguration struct {
	CorsRules []CorsRule `json:",omitempty"`
}

// CorsRule is autogenerated from the json schema
type CorsRule struct {
	ExposedHeaders []string `json:",omitempty"`
	AllowedMethods []string `json:",omitempty"`
	AllowedOrigins []string `json:",omitempty"`
	AllowedHeaders []string `json:",omitempty"`
	MaxAge         *int     `json:",omitempty"`
	Id             *string  `json:",omitempty"`
}

// ObjectLockConfiguration is autogenerated from the json schema
type ObjectLockConfiguration struct {
	ObjectLockEnabled *string         `json:",omitempty"`
	Rule              *ObjectLockRule `json:",omitempty"`
}

// ObjectLockRule is autogenerated from the json schema
type ObjectLockRule struct {
	DefaultRetention *DefaultRetention `json:",omitempty"`
}

// DefaultRetention is autogenerated from the json schema
type DefaultRetention struct {
	Years *int    `json:",omitempty"`
	Days  *int    `json:",omitempty"`
	Mode  *string `json:",omitempty"`
}

// LoggingConfiguration is autogenerated from the json schema
type LoggingConfiguration struct {
	DestinationBucketName *string `json:",omitempty"`
	LogFilePrefix         *string `json:",omitempty"`
}

// ReplicationConfiguration is autogenerated from the json schema
type ReplicationConfiguration struct {
	Role  *string           `json:",omitempty"`
	Rules []ReplicationRule `json:",omitempty"`
}

// ReplicationRule is autogenerated from the json schema
type ReplicationRule struct {
	Status                  *string                  `json:",omitempty"`
	Destination             *ReplicationDestination  `json:",omitempty"`
	Filter                  *ReplicationRuleFilter   `json:",omitempty"`
	Priority                *int                     `json:",omitempty"`
	SourceSelectionCriteria *SourceSelectionCriteria `json:",omitempty"`
	Id                      *string                  `json:",omitempty"`
	Prefix                  *string                  `json:",omitempty"`
	DeleteMarkerReplication *DeleteMarkerReplication `json:",omitempty"`
}

// ReplicationDestination is autogenerated from the json schema
type ReplicationDestination struct {
	AccessControlTranslation *AccessControlTranslation `json:",omitempty"`
	Account                  *string                   `json:",omitempty"`
	Metrics                  *Metrics                  `json:",omitempty"`
	Bucket                   *string                   `json:",omitempty"`
	EncryptionConfiguration  *EncryptionConfiguration  `json:",omitempty"`
	StorageClass             *string                   `json:",omitempty"`
	ReplicationTime          *ReplicationTime          `json:",omitempty"`
}

// AccessControlTranslation is autogenerated from the json schema
type AccessControlTranslation struct {
	Owner *string `json:",omitempty"`
}

// Metrics is autogenerated from the json schema
type Metrics struct {
	Status         *string               `json:",omitempty"`
	EventThreshold *ReplicationTimeValue `json:",omitempty"`
}

// ReplicationTimeValue is autogenerated from the json schema
type ReplicationTimeValue struct {
	Minutes *int `json:",omitempty"`
}

// EncryptionConfiguration is autogenerated from the json schema
type EncryptionConfiguration struct {
	ReplicaKmsKeyID *string `json:",omitempty"`
}

// ReplicationTime is autogenerated from the json schema
type ReplicationTime struct {
	Status *string               `json:",omitempty"`
	Time   *ReplicationTimeValue `json:",omitempty"`
}

// ReplicationRuleFilter is autogenerated from the json schema
type ReplicationRuleFilter struct {
	Prefix    *string                     `json:",omitempty"`
	And       *ReplicationRuleAndOperator `json:",omitempty"`
	TagFilter *TagFilter                  `json:",omitempty"`
}

// ReplicationRuleAndOperator is autogenerated from the json schema
type ReplicationRuleAndOperator struct {
	TagFilters []TagFilter `json:",omitempty"`
	Prefix     *string     `json:",omitempty"`
}

// SourceSelectionCriteria is autogenerated from the json schema
type SourceSelectionCriteria struct {
	SseKmsEncryptedObjects *SseKmsEncryptedObjects `json:",omitempty"`
}

// SseKmsEncryptedObjects is autogenerated from the json schema
type SseKmsEncryptedObjects struct {
	Status *string `json:",omitempty"`
}

// DeleteMarkerReplication is autogenerated from the json schema
type DeleteMarkerReplication struct {
	Status *string `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Value *string `json:",omitempty"`
	Key   *string `json:",omitempty"`
}
