package resource

import "github.com/aws-cloudformation/aws-cloudformation-rpdk-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	BucketName *encoding.String `json:"BucketName,omitempty"`
	Key        *encoding.String `json:"Key,omitempty"`
	Content    *encoding.String `json:"Content,omitempty"`
	ACL        *encoding.String `json:"ACL,omitempty"`
}
