package errs

// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
type ValidationError struct {
	CausingErrors  []error
	Keyword        string
	SchemaLocation string
}

//func (e ValidationError) Error() string {
//	return fmt.Sprintf("Resource of type '%s' with identifier '%s' was not found.\n%s", e.ResourceTypeName, e.ResourceIdentifier, e.Err)
//}

func GetCausingExceptions() []error {
	return nil
}

func GetKeyword() string {
	return ""
}

func GetSchemaLocation() string {
	return ""
}
