// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name        *string `json:",omitempty"`
	Owner       *string `json:",omitempty"`
	Description *string `json:",omitempty"`
	Homepage    *string `json:",omitempty"`
	OauthToken  *string `json:",omitempty"`
	URL         *string `json:",omitempty"`
}
