package main

import (
	"github.com/aws-cloudformation/aws-cloudformation-rpdk-go-plugin/proxy"
	"{{ path }}"
)

//****This file is autogenerated, do not edit; changes will be undone by the next 'generate' command.****

//main is the entry point of the applicaton.
//**Starts the serice proxy. The type passed to the Start function must implement the InvokerHandler interface.
//type InvokeHandler interface {
//	CreateRequest(request *ResourceHandlerRequest, context RequestContext) (*ProgressEvent, error)
//	DeleteRequest(request *ResourceHandlerRequest, context RequestContext) (*ProgressEvent, error)
//	ListRequest(request *ResourceHandlerRequest, context RequestContext) (*ProgressEvent, error)
//	ReadRequest(request *ResourceHandlerRequest, context RequestContext) (*ProgressEvent, error)
//	UpdateRequest(request *ResourceHandlerRequest, context RequestContext) (*ProgressEvent, error)
//}
//
func main() {

	r := resource.New()

	proxy.Start(r)

}
